import Head from 'next/head'
import dynamic from 'next/dynamic';
import ThreeTierPricing from '@/components/pricing'

const Search = dynamic(
  () => import('shop/Search').then((mod) => mod.Search),
  {
    ssr: true,
  }
);

export function Pricing({ test }) {
  return (
    <>
      <Head>
        <title>Pricing | Next MF app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThreeTierPricing test={test}/>
        <Search />
      </main>
    </>
  )
}

export async function getServerSideProps({ query }) {
  const test = Date.now() % 500
  return {
    props: {
      test,
    },
  };
}

export default Pricing
